mrBots/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path("acercade", views.acercade, name="acercade"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registrarse/', include('usuarios.urls')),
    path('', include('productos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path, include
from . import views

app_name = "productos"
urlpatterns = [
    path('filtro_categoria/<int:id>', views.filtro_categoria, name="filtro_categoria"),
    path('crear_producto/', views.crear_producto, name="crear_producto"),
    path("productos/ver_productos/<int:id>", views.ver_productos, name='ver_productos'),
    path("productos/<int:id>/borrar", views.borrarProducto, name="borrarProducto"),
    path("productos/editar_producto/<int:id>", views.editar_producto, name="editar_producto"),
    path('carrito', views.carrito, name="carrito"),
    path('carrito/<int:id>/agregarCarrito', views.agregarCarrito, name="agregarCarrito"),
    path("productos/<int:id>/borrar_carrito", views.borrar_carrito, name="borrar_carrito"),
    path("productos/<int:id>/editar_carrito", views.editar_carrito, name="editar_carrito"),
    path("productos/search", views.search, name="search"),
    path("productos/contacto", views.contacto, name="contacto")
]

productos/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import AbstractUser, User

class Categorias(models.Model):
    categoria = models.CharField(max_length=64, null=False)

    def __str__(self):
        return f"{self.categoria}"


class Productos(models.Model):
	categoria = models.ForeignKey(Categorias, on_delete=models.CASCADE, related_name="clasificacion_seccion")
	fecha_creacion = models.DateTimeField(auto_now_add=True)
	titulo = models.CharField(max_length=250, null=False)
	contenido = models.CharField(max_length=2000, null=False)
	imagen = CloudinaryField('imagenes')
	precio = models.CharField(max_length=10, default=0)
	precio_oferta = models.CharField(max_length=10, default=0)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usuario")

	def __str__(self):
		return f"{self.fecha_creacion} - {self.titulo} - ${self.precio} ({self.usuario})"


class Carritos(models.Model):
	usuario =  models.ForeignKey(User, on_delete = models.SET_NULL, null = True)
	producto = models.ForeignKey(Productos, null=True, blank=True, on_delete=models.CASCADE)
	fecha_creacion = models.DateTimeField(auto_now_add=True)
	cantidad = models.CharField(default=1, max_length=3)


	def __str__(self):
		return f"{self.producto} - ({self.usuario})"

productos/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm

from django.contrib.auth.models import User
from .models import Productos, Carritos

class ProductosForm(forms.ModelForm):
    class Meta:
        model = Productos
        fields = "__all__"
        exclude = ('usuario',)

    def __init__(self, *args, **kwargs):
        super(ProductosForm, self).__init__(*args, **kwargs)
        self.fields["categoria"].widget.attrs.update({'class': 'pub_categoria form-select','id':"floatingSelectGrid", 'aria-label': "Floating label select example"})
        self.fields["titulo"].widget.attrs.update({'class': 'form-control pub_titulo', 'id':"floatingInputGrid", 'placeholder':"titulo del producto", 'value':"escriba aquí el titulo del producto"})
        self.fields["precio"].widget.attrs.update({'class':"form-control", 'aria-label':"Amount (to the nearest dollar)"})
        self.fields["contenido"].widget.attrs.update({'class': 'form-control pub_titulo', 'id':"floatingInputGrid", 'placeholder':"contenido", 'value':"escriba el contenido del producto"})

        

class SearchForm(forms.Form):
    titulo = forms.CharField(max_length=30, required = False)
    ORDER_OPCIONES = (
        ("titulo", "Titulo"),
        ("Fecha",(
            ("antiguo", "Antiguo"),
            ("nuevo", "Nuevo"))
        ))
    orden = forms.ChoiceField(choices=ORDER_OPCIONES, required = False,
        initial="nuevo")

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields["titulo"].widget.attrs.update({"class":"form-control me-2", "type":"search", "placeholder":"Buscar", "aria-label":"Search"})


class CarritoForm(forms.ModelForm):
    class Meta:
        model = Carritos
        fields = ('cantidad',)

    def __init__(self, *args, **kwargs):
        super(CarritoForm, self).__init__(*args, **kwargs)
        self.fields["cantidad"].widget.attrs.update({'type':"number",'value':"{{'cantidad'}}",'class':"form-control md-2", 'id':"cantidad", 'name':"cantidad"})

productos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout,login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .forms import ProductosForm, SearchForm, CarritoForm
from .models import Productos, Categorias, Carritos
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import PasswordChangeForm
from django.core.paginator import Paginator
from django.utils import timezone
from django.contrib.auth.models import  User
#para enviar gmail
from django.conf import settings
from django.template.loader import get_template # template visto desde el gmail
from django.core.mail import EmailMultiAlternatives

# Create your views here.
@login_required
def crear_producto(request):
	#BUSQUEDA--------------------------------------------------------------------------------------------------------
	if request.GET:
		search_form = SearchForm(request.GET)
	else:
		search_form = SearchForm()
	#FIN BUSQUEDA-----------------------------------------------------------------------------------------------------
	
	#CREAR PRODUCTO---------------------------------------------------------------------------------------------------
	if request.method == "POST":
		form= ProductosForm(request.POST,request.FILES)
		if form.is_valid():
			producto=form.save(commit=False)
			producto.usuario = request.user
			producto.save()
			return redirect("productos:ver_productos", producto.id)
		else:
			contexto={"form":form,
					"search_form":search_form,
			}
			return render(request, "productos/crearProductos.html",contexto)
	form = ProductosForm()
	productos : Productos.objects.all()
	contexto={"form":form,
			"search_form":search_form,
			}
	return render(request, "productos/crearProductos.html",contexto)

def ver_productos(request, id):
	#BUSQUEDA--------------------------------------------------------------------------------------------------------
	if request.GET:
		search_form = SearchForm(request.GET)
	else:
		search_form = SearchForm()
	#FIN BUSQUEDA-----------------------------------------------------------------------------------------------------
	#ver productos----------------------------------------------------------------------------------------------------
	producto = get_object_or_404(Productos,id=id)
	#PAGINACION-----------------------------------------------------------
	productos= Productos.objects.all().order_by("-fecha_creacion")[0:10]
	paginate = Paginator(productos, 3 )
	page_number = request.GET.get('page')
	page_obj = paginate.get_page(page_number)
	#agregar Carrito----------------------------------------------------------------
	form_carrito = CarritoForm()
	carritos = Carritos.objects.order_by("-fecha_creacion")
	lista_categorias = Categorias.objects.all()
	form = SearchForm()
	contexto ={
		"producto" : producto,		
		'form':form,
		'search_form':search_form,	
		"page_obj" : page_obj,
		"lista_categorias": lista_categorias,
		'carritos':carritos,
		'form_carrito': form_carrito,
		}
	return render(request,"productos/ver_productos.html", contexto)

@login_required
def borrarProducto(request, id):
  	producto = get_object_or_404(Productos, id=id)
  	producto.delete()
  	return redirect("index")
@login_required
def editar_producto(request, id):
    producto = get_object_or_404(Productos, id=id)
    if request.method == "POST":  
        user = User.objects.get(username=request.user)   
        producto.usuario = user
        form = ProductosForm(data=request.POST, files=request.FILES, instance=producto)
        if form.is_valid():
            form.save()
            return redirect("index")
    else:
        form = ProductosForm(instance = producto)
        return render(request, 'productos/editar_producto.html', {
            "producto": producto,
            "form": form
        })

def search(request):
	if request.GET:
		search_form = SearchForm(request.GET)
	else:
		search_form = SearchForm()

	filtro_titulo = request.GET.get("titulo", "")
	orden_post = request.GET.get("orden", None)
	lista_productos = Productos.objects.filter(titulo__icontains = filtro_titulo)

	if orden_post == "titulo":
		lista_productos= lista_productos.order_by("titulo")
	elif orden_post == "antiguo":
		lista_productos= lista_productos.order_by("fecha_creacion")
	elif orden_post == "nuevo":
		lista_productos= lista_productos.order_by("-fecha_creacion")

	#paginate
	
	paginate = Paginator(lista_productos, 12)
	page_number = request.GET.get('page')
	page_obj = paginate.get_page(page_number)

	form = SearchForm()
	lista_categorias = Categorias.objects.all()		
	contexto = { "form":form,
				 "lista_productos":lista_productos,
				 "search_form":search_form,
				 "lista_categorias": lista_categorias,
				 "page_obj" : page_obj,
				 }
	return render(request, "productos/search.html",contexto)


def filtro_categoria(request, id):
    categoria = get_object_or_404(Categorias, id=id)
    queryset = Productos.objects.all()
    queryset = queryset.filter(categoria=categoria)
    lista_categorias = Categorias.objects.all()
    contexto = {
        "lista_productos": queryset,
        "lista_categorias": lista_categorias,
        "categoria_seleccionada": categoria,
        }
    return render(request,"index.html", contexto)
@login_required
def carrito(request):
	#BUSQUEDA--------------------------------------------------------------------------------------------------------
	if request.GET:
		search_form = SearchForm(request.GET)
	else:
		search_form = SearchForm()
	
	#FIN BUSQUEDA-----------------------------------------------------------------------------------------------------
	
	carritos = Carritos.objects.all()
	usuario = request.user
	#total de productos
	total= 0
	for x in carritos:
		if request.user == x.usuario:
			total+= int(x.producto.precio_oferta)
			total*= int(x.cantidad)
			form = CarritoForm()

	#modificar cantidad de productos en el carrito
	lista_categorias = Categorias.objects.all()
	form = CarritoForm()
	contexto ={
    "search_form":search_form,
	'carritos':carritos,
	'usuario':usuario,
	'total':total,
	'form_carrito':form,
	"lista_categorias": lista_categorias,
    }
	return render(request,"carritos/carritos.html", contexto)

@login_required
def agregarCarrito(request, id):
	if request.GET:
		search_form = SearchForm(request.GET)
	else:
		search_form = SearchForm()
	#FIN BUSQUEDA-----------------------------------------------------------------------------------------------------
	
	#agregar carrito----------------------------------------------------------------------------------------------------
	
	producto = Productos.objects.get(pk=id)
	if request.method == "POST":
		form = CarritoForm(request.POST)
		user = User.objects.get(username=request.user)
		if form.is_valid():
			carrito = form.save(commit=False)
			carrito.usuario = request.user
			carrito.producto = producto
			carrito.save()
			return redirect("productos:carrito")
	else:
		return redirect("ver_productos", producto.id)
@login_required
def borrar_carrito(request, id):
	carrito = get_object_or_404(Carritos, id=id)
	carrito.delete()
	return redirect("index")
@login_required
def editar_carrito(request, id):
    carrito = get_object_or_404(Carritos, id=id)
    if request.method == "POST":  
        user = User.objects.get(username=request.user)   
        carrito.usuario = user
        form = CarritoForm(data=request.POST, files=request.FILES, instance=carrito)
        if form.is_valid():
            form.save()
            return redirect("productos:carrito")
    else:
        form = CarritoForm(instance = carrito)
        return render(request, 'carritos/carritos.html', {
            "carrito": carrito,
            "form": form
        })


def send_email(mail, contenido):
	contexto = {'mail':mail, 'contenido':contenido}
	template = get_template('correo.html')
	content = template.render(contexto)

	email = EmailMultiAlternatives(
		'Correo Electronico', #titulo del correo
		'MrBots',  #mensaje que describe el correo
		settings.EMAIL_HOST_USER,#cuenta de correo utulizando 
		[mail],
		cc=['Mrbots.allsoftware@gmail.com']#lista de correos que se envia el contenido (destinatario)
		)
	email.attach_alternative(content, 'text/html')
	email.send()

def contacto(request):
	if request.method == 'POST':
		mail = request.POST.get('mail')
		contenido = request.POST.get('contenido')
		send_email(mail, contenido)
	contexto = {}
	return render(request, 'productos/contacto.html', contexto)

#modo backentd
#def send_email(mail, contenido):
#	contexto = {'mail':mail, 'contenido':contenido}
#	template = get_template('correo.html')
#	content = template.render(contexto)
#
#	email = EmailMultiAlternatives(
#		'Correo Electronico', #titulo del correo
#		'MrBots',  #mensaje que describe el correo
#		settings.EMAIL_HOST_USER,#cuenta de correo utulizando 
#		[mail],#lista de correos que se envia el contenido (destinatario)
#		)
#	email.attach_alternative(content, 'text/html')
#	email.send(content)

#def contacto(request):
#	if request.method == 'POST':
#		mail = request.POST.get('mail')
#		contenido = request.POST.get('contenido')
#		send_email(mail, contenido)
#	contexto = {}

#	return render(request, 'productos/contacto.html', contexto)

productos/templates/productos/contacto.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary%}

{% block contenido %}

<h2>Enviar Correo</h2>
<form action="#" method="POST">
	{% csrf_token %}

	 <!---<div class="form-floating">
      <input type="hidden" name="mail"class = 'form-control pub_titulo' id="floatingInputGrid", placeholder ="Mrbots.allsoftware@gmail.com" value="Mrbots.allsoftware@gmail.com"><br>
    </div>--->	
	<input type="text" name="mail" placeholder="demo@example.com"><br>
	<input type="textarea" name="contenido" placeholder="contenido">
	<input type="submit" style="font-size: 26px" value="Enviar">
</form>

{% endblock%}

productos/templates/productos/crearProductos.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary%}
{% block contenido %}
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
	<div class="card border-info mb-3">
		<form method="POST" enctype="multipart/form-data" action="{% url 'productos:crear_producto' %}">
			<div class="text-center">
			<h1>Nuevo Producto</h1>
			</div>
			<a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'img/logo2.5.png' %}" class="rounded mx-auto d-block" width="90" height="90" alt="Logo Mr Bots"></a>
				{% csrf_token %}

			  <div class="col-md">
			    <div class="form-floating">
			      {{ form.titulo }}{{ form.titulo.errors }}
			      <label for="floatingInputGrid">Titulo del producto</label>
			    </div>
			    <hr>
			  </div>
			  <div class="col-md">				  
			    <div class="form-floating">
			      {{ form.categoria }} {{ form.categoria.errors }}
			      <label for="floatingSelectGrid">selecciona la categoria</label>      
			    </div>
			  </div>
			  <hr>
			  <div class="col-md">
			    <div class="form-floating">
		        {{ form.contenido }}{{ form.contenido.errors }}
		      <label for="floatingInputGrid">Contenido</label>
			    </div>
			    <hr>
			  </div>
		      <div class="form-group row">
		        <label for="imagen_input">Adjuntar Imagen:</label> {{ form.imagen }} {{ form.imagen.errors }}
		      </div>
		      <hr>
		      <div class="row g-2">
				<div class="col-md">
				  <div class="form-floating">
				  <span class="input-group-text">precio   $</span>
				  	{{form.precio}} {{form.precio.errors}}
				  <span class="input-group-text">.00</span>
				  </div>
				</div>
				<div class="col-md">
    			 <div class="form-floating">
				  <span class="input-group-text">precio oferta  $</span>
				  	{{form.precio_oferta}} {{form.precio_oferta.errors}}
				  <span class="input-group-text">.00</span>
				</div>
			  </div>
			</div>
			<hr>
			<button class="btn btn-primary" type="submit">Crear</button>
		</form>
	</div>
</div>
  </div>
</div>

{% endblock%}

productos/templates/productos/cuadriculaproductos.html
{% load static %}
  {% load cloudinary%}
{% for productos in lista_productos %}
 <div class="col md-2">
    <div class="card h-100" style="width: 18rem;">
        <img src="{{ productos.imagen.url }}"  class="card-img-top rounded-circle" alt="foto del Producto" width="250" height="250" >
        <div class="card-body">
          <h5 class="card-title">{{productos.titulo}}</h5>
          <p class="card-text">{{productos.contenido | truncatechars:30 }}</p>
          <p class="card-text"><del>${{productos.precio}}</del></p>
          <p class="card-text">${{ productos.precio_oferta }}</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">{{productos.fecha_creacion}}</small>
        </div>
        <a href="{% url 'productos:ver_productos' productos.id %}" class="btn btn-primary">Ver Producto</a>
    </div>
  </div>
  
  {% endfor %}

productos/templates/productos/editar_producto.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary%}
{% block contenido %}
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
	<div class="card border-info mb-3">
<form method="POST">
	<div class="text-center">
	<h1>Editar Producto</h1>
	</div>
	<img src="#" class="rounded mx-auto d-block" width="160" height="160" alt="...">
		{% csrf_token %}
			{{ form }}
	<button class="btn btn-primary" type="submit">Confirmar</button>
</form>
	</div>
</div>
  </div>
</div>
{% endblock%}

productos/templates/productos/listaProductos.html
{% load static %}
{% load cloudinary%}
  {% for productos in lista_productos %}

<div class="list-group">
  <a href="{% url 'productos:ver_productos' productos.id %}" class="list-group-item list-group-item-action active" aria-current="true">
    <div class="d-flex w-100 justify-content-between">
      <img src="{{ productos.imagen.url }}"  class="rounded-circle" alt="foto del Producto" width="50" height="50" >
      <small>{{productos.fecha_creacion}}</small>
    </div>
    <p class="mb-1">{{productos.titulo | truncatechars:15 }}</p>
    <small>{{productos.contenido | truncatechars:40 }}</small>
  </a>
</div>
  <hr>
	 {% empty %}
          <div class="col">
            <div class="card h-100">
              No hay Productos en ésta Categoria.
            </div>
          </div>
  {% endfor %}

productos/templates/productos/search.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary%}
{% block tituloHead%}
Buscar
{% endblock%}

{% block contenido %}
<form action="" >
	{{ form }}
	<button class="btn btn-outline-succes" type="submit">Buscar</button> 
</form>

<h1>Resultado</h1>
	<div class="row  row-col-md-3">
	{% include 'productos/cuadriculaproductos.html'%}
    </div>

	<nav aria-label="Page navigation example">
	  {% if page_obj.has_next or page_obj.has_previous %}
	    <ul class="pagination">
	    {% if page_obj.has_previous %}
		    <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-double-left" viewBox="0 0 16 16">
			  <path fill-rule="evenodd" d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
			  <path fill-rule="evenodd" d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/></svg>Anterior</a>
			</li>
		{% endif %}
		{% for page in page_obj.paginator.page_range %}
		    <li class=" page-item {% if page_obj.number == page %}active{% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a>
		    </li>
		{% endfor %}
		{% if page_obj.has_next %}
		    <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Siguiente<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-double-right" viewBox="0 0 16 16">
		      <path fill-rule="evenodd" d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z"/>
		      <path fill-rule="evenodd" d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z"/></svg></a>
		    </li>
		{% endif %}
		</ul>
	  {% endif %}
	</nav>
</div>

<hr>
{% endblock %}

productos/templates/productos/search_form.html
<form method="GET" style="padding-top: 20px;" action="{% url 'productos:search' %}" class="d-flex">
        {{ search_form.titulo }}
        <button class="btn btn-outline-succes" type="submit">Buscar</button>       
 </form>

productos/templates/productos/ver_productos.html
{% extends 'base.html'%}
{% load static %}
{% load cloudinary%}
{% block contenido %}
<div class="alert alert-info" role="alert">{{ producto.categoria }}</div>
  <div class="container">
  <br>
  <div class="row">
  	<div class="col-sm-8">
  	  <div class="card text-center">
	  	  <div class="card-header">
          <div class="col-sm" >
            <img src="{{ producto.imagen.url }}" class="rounded" width="250" height="250"  alt="Imagen del producto">
          </div>
	  		  
	        {{ producto.titulo }}
	  	  </div>
			    <div class="card-body">   
					<p class="card-text">{{producto.contenido}}</p>
				</div>
        <p class="card-text"><del>${{producto.precio}}</del></p>
            <p class="card-text">${{ producto.precio_oferta }}</p>
			  <div class="card-footer text-muted">
			    {{producto.fecha_creacion}}}         
         
			  </div>
        {% if request.user == producto.usuario %}
          <a href="{% url 'productos:editar_producto' producto.id %}" class="btn btn-primary">Editar Producto</a>

          <a href="{% url 'productos:borrarProducto' producto.id %}" class="btn btn-primary">Borrar Producto</a>
        {% endif %}
        </div>        
    </div>
    {% if request.user.is_authenticated %}
     <div class="col-sm-4">
       <form method="POST" action="{% url 'productos:agregarCarrito' producto.id %}" enctype="multipart/form-data">
         {% csrf_token %}         
          <h5 class="card-title">agregar al carrito?:</h5>
          <div class="row">
            <div class="col-sm"><button type="button" class="btn btn-info" id="remove">-</button></div>
              <div class="col-sm-8">{{ form_carrito.cantidad }} </div>
                <div class="col-sm"><button type="button" class="btn btn-info" id="add">+</button></div>     
                 <button type="submit" class="btn btn-primary mb-2">agreagar al carrito<span class="fas fa-shopping-cart"></span></button>
          </div>
        </form>
    </div>
    {% else %}
    <div class="col-sm-4">pubicidad
      <div class="col-sm">
            <img src="{% static 'img/pub.gif' %}" class="img-thumbnail"  alt="publicidad" width="400" height="300">
        </div>
    </div>
    {% endif %}
  </div>
</div>


<hr>
<h1>Productos autor</h1>
<hr><hr>
<div class="row  row-cols-sd-4">
  {% include 'productos/cuadriculaproductos.html' with lista_productos=page_obj %}
</div>
  <!---paginate--->
    <nav aria-label="Page navigation example">
    {% if page_obj.has_next or page_obj.has_previous %}
      <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-double-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
        <path fill-rule="evenodd" d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/></svg>Anterior</a>
      </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        <li class=" page-item {% if page_obj.number == page %}active{% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a>
        </li>
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Siguiente<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-double-right" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z"/>
          <path fill-rule="evenodd" d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z"/></svg></a>
        </li>
    {% endif %}
    </ul>
    {% endif %}
  </nav>
</div>

{% endblock %}