mrBots/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path("acercade", views.acercade, name="acercade"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registrarse/', include('usuarios.urls')),
    path('', include('productos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path, include
from . import views

app_name = "productos"
urlpatterns = [
    path('filtro_categoria/<int:id>', views.filtro_categoria, name="filtro_categoria"),
    path('crear_producto/', views.crear_producto, name="crear_producto"),
    path("productos/ver_productos/<int:id>", views.ver_productos, name='ver_productos'),
    path("productos/<int:id>/borrar", views.borrarProducto, name="borrarProducto"),
    path("productos/editar_producto/<int:id>", views.editar_producto, name="editar_producto"),
    path('carrito', views.carrito, name="carrito"),
    path('carrito/<int:id>/agregarCarrito', views.agregarCarrito, name="agregarCarrito"),
    path("productos/<int:id>/borrar_carrito", views.borrar_carrito, name="borrar_carrito"),
    path("productos/<int:id>/editar_carrito", views.editar_carrito, name="editar_carrito"),
    path("productos/search", views.search, name="search"),
    path("productos/contacto", views.contacto, name="contacto")
]

usuarios/urls.py
from django.urls import path, include
from . import views

app_name = "usuarios"
urlpatterns = [
    path('', views.registrarse, name="registrarse"),
]

templates/base.html
{% load static %}
{% load cloudinary%}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>MrBots {{ title }}</title>
	<!--bootstrap 5-->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>		
	{% include 'navbar.html' %}
	{% include 'menu.html' %}
	<div class="container">	
		<div class="row" >
		{% block contenido %}

		{% endblock %}
		</div>
	</div>
	<br><br>
</div>
	
	{% include 'footer.html' %}
	<script type="text/javascript" src="{% static 'js/carrito.js' %}"></script>
	<!--scripts de bootstrp-->
	<script src="https://kit.fontawesome.com/1356b06277.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

templates/correo.html
{% load inlinecss %}
{% inlinecss 'css/estilos.css' %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1>Hola {{mail}}, gracias por comunicarse con Mr Bots All Software</h1>
	<p class="parrafo"> 
		Ahora que nos has encontrado podras descubrir todos los productos imprensindibles sobre tecnologias.
	</p>
	<p class="parrafo"> En este caso has seleccionado preguntar por:</P>
	<p class="parrafo">{{contenido}}, en breve le brindaremos informacion</p>
	<br><hr>
	<hr>
	<br>
	<h3>En Mr Bots All Software contamos con: </h3>
	<p>Con un equipo de especialistas en tecnología altamente capacitados a bordo, trabajamos junto a vos para explorar, impulsar y potenciar tu proyecto.</p><br>
    <p>Nos motiva una gran misión: ayudarte a convertir en realidad tus sueños creando experiencias digitales de alta calidad que le aporten un valor agregado a tu empresa y que tengan un impacto significativo en su entorno.</p> 

	<p> Excelencia en el diseño y desarrollo de software para construir el futuro.,</p>https://hidden-sea-56387.herokuapp.com/
</body>
</html>
{% endinlinecss %}

templates/footer.html
{% load static %}
{% load cloudinary%}
<footer class="dark bg-primary">
	<div class="row">
	    <div class="col-md">
    	<hr>
    	<p>Todos los Derechos Reservados &copy; 2021  - Villordo Cristian</p><br><br>
    	<p>Mr Bots all software</p>
    	<p style="color:white;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
		<path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/></svg> </a>
		<a href="https://www.facebook.com/Mr-Bots-108838081304828" style="color:white;">Mr. Bots </a></p>

       <p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
	   	<path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
		</svg><a href="https://www.instagram.com/mr._bots_allsoftware/" style="color:white;"> Instagram</a></p>

		<p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
	  	  <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
		  </svg><a href="https://www.linkedin.com/in/cristian-villordo-2a80a71b6/" style="color:white;"> Linkedin</a></p>
						
		 </div>
		  	<div class="col-md"><br>
				<img src="{% static 'img/Mr_Bots.png' %}" class="img-thumbnail"  alt="publicidad" width="300" height="500">
			</div>
		</div>
</footer>

templates/index.html
{% extends 'base.html' %}

  {% block contenido %}
  <!---seleccion de categorias--->
  <div class="container">
     	<h2>Productos</h2>
    {% if categoria_seleccionada %}
        <div class="alert alert-info" role="alert">{{ categoria_seleccionada }}</div>
    {% else %}
        <div class="alert alert-info" role="alert">Todos los Productos</div>
    {% endif %}
   <!---lista de productos en card--->
    <div class="row  row-col-md-3">
	  {% include 'productos/cuadriculaproductos.html' with lista_productos=page_obj %}
	</div>
	<!---paginate--->
	<nav aria-label="Page navigation example">
	  {% if page_obj.has_next or page_obj.has_previous %}
	    <ul class="pagination">
	    {% if page_obj.has_previous %}
		    <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-double-left" viewBox="0 0 16 16">
			  <path fill-rule="evenodd" d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
			  <path fill-rule="evenodd" d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/></svg>Anterior</a>
			</li>
		{% endif %}
		{% for page in page_obj.paginator.page_range %}
		    <li class=" page-item {% if page_obj.number == page %}active{% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a>
		    </li>
		{% endfor %}
		{% if page_obj.has_next %}
		    <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Siguiente<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-double-right" viewBox="0 0 16 16">
		      <path fill-rule="evenodd" d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z"/>
		      <path fill-rule="evenodd" d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z"/></svg></a>
		    </li>
		{% endif %}
		</ul>
	  {% endif %}
	</nav>
</div>
	<br><br><br><br>

	<!---lista de productos--->
	  <div class="row">	
	  <div class="col-md-12">
	  	{% include 'productos/listaProductos.html' with lista_productos=lista_productos%}
	  </div>		
	  </div>
	  
  {% endblock %}

templates/menu.html
{% load static %}
{% load cloudinary%}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categorias
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li> {% for categoria in lista_categorias %}
                      <a class="dropdown-item" href="{% url 'productos:filtro_categoria' categoria.id%}">{{ categoria }}</a>
                  {% endfor %}
                </li>
            </ul>
          </li>

          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'acercade' %}">Acerca de...</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'productos:contacto' %}">Contacto</a>
          </li>
          {% if perms.sitio.add_producto %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'productos:crear_producto' %}" tabindex="-1" aria="true">Nuevo Producto</a>
          </li>
          {% endif %}
        </ul>
        {% include 'productos/search_form.html' %}
      </div>
    </div>
  </nav>

templates/navbar.html
 {% load static %}
 {% load cloudinary%}
    {% if request.user.is_authenticated %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'img/logo2.5.png' %}" class="rounded mx-auto d-block" width="90" height="90" alt="Logo Mr Bots"></a><a class="navbar-brand" href="{% url 'index' %}"> Mr Bots</a>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="nav justify-content-end">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">logout <span class="fas fa-user"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'productos:carrito' %}">Carrito <span class="fas fa-shopping-cart"></span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% else %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'img/logo2.5.png' %}" class="rounded mx-auto d-block" width="90" height="90" alt="Logo Mr Bots"></a>Mr Bots
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="nav justify-content-end">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login <span class="fas fa-user"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'usuarios:registrarse' %}">Registro <span class="fas fa-user-plus"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'productos:carrito' %}">Carrito <span class="fas fa-shopping-cart"></span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% endif %}

templates/sobre_nosotros.html
{% load static %}
{% load cloudinary%}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Acerca de nosotros</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/sobre_nosotros.css' %}">
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>SOBRE MR BOTS</h3>
				<div class="d-flex justify-content-end social_icon">
					<a href="https://www.facebook.com/Mr-Bots-108838081304828"><span><i class="fab fa-facebook-square"></i></span></a>
					<a href="https://www.instagram.com/mr._bots_allsoftware/"> <span><svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
	   	<path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
		</svg></a></span>

		<a href="https://www.linkedin.com/in/cristian-villordo-2a80a71b6/"><span><svg xmlns="http://www.w3.org/2000/svg" width="55" height="55" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
	  	  <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
		  </svg> </a></span>
				</div>
			</div>
			<div class="card-body">
					<<div class="row align-items-center remember">
						Es una empresa argentina dedicada al comercio electrónico y al desarrollo de aplicaciones y paginas web. En la pagina los usuarios pueden ver el catalogo de los productos disponibles con sus ofertas correspondientes, para proceder  una compra o llevar al carrito para ver la totalidad de los productos seleccionados, o tambien para consultar o contactar con el propietario, se debera registrar, donde se pedira datos basicos al usuario para registrarse.						
					</div>
					<div class="row align-items-center remember">Ayudamos a crear experiencias de marketing que integran a los clientes con procesos y tecnología para lograr un enfoque eficiente que cause un impacto positivo en los objetivos del negocio.
					</div>
					<div class="row align-items-center remember">
					trabajamos junto a vos para explorar, impulsar y potenciar tu proyecto.
					Nos motiva una gran misión: ayudarte a convertir en realidad tus sueños creando experiencias digitales de alta calidad
					que le aporten un valor agregado a tu empresa y que tengan un impacto significativo en su entorno.

					Excelencia en el diseño y desarrollo de software para construir el futuro.
					</div>
			</div>
			<div class="form-group">
					<a href="{% url 'index' %}" class="white-mode btn float-right login_btn">Ir a Mr Bots</a>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>
			